### ISSUE TITLE
Missing cases

### ISSUE THREAD

**Issue by lc3t35** [jonsamp/react-native-expo-svg#1]
These items can be found and should be discarded :

xmlns: 
xlink

These items should be converted :

stroke-width -> strokeWidth
stroke-linecap -> strokeLinecap
stroke-linejoin -> strokeLinejoin

If a "filter" directive is used in the SVG file, it is not supported by expo SVG, so it should stop import with a warning (file should be corrupted)

**Comment by jonsamp** [comment]
Hi @lc3t35,

Thanks for your comment and feedback! I just updated the package to reflect your changes.

Remove xmlns and xlink: https://github.com/jonsamp/react-native-expo-svg/blob/master/index.js#L11

Convert stroke-*: https://github.com/jonsamp/react-native-expo-svg/blob/master/index.js#L101-L103

Error if `<filter` exists: https://github.com/jonsamp/react-native-expo-svg/blob/master/index.js#L45-L50

You can get the newest version `1.1.1` with:

```bash
npm i -g react-native-expo-svg
```
