### ISSUE TITLE
import { Svg } from "expo" no longer supported since SDK 34

### ISSUE THREAD

**Issue by RichardPK** [jonsamp/react-native-expo-svg#2]
As in the title - the import method `import { Svg } from "expo"` is no longer supported in the latest Expo SDK (34 at the time of writing).

The new route is `import Svg from "react-native-svg"`, but this creates the following error:

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

https://docs.expo.io/versions/latest/sdk/svg/

**Comment by RichardPK** [comment]
I've found a workaround compatible with this new way of importing the react-native-svg library:

**NEW:**

`import React from "react";
import Svg, { G, Rect, Circle, Ellipse, Text, TSpan, Path } from "react-native-svg";

function ScorezeromarksIcon({ style, outer }) {
  return (
    <Svg style={style} width="100%" height="100%" viewBox="0 0 29 29">
      <Path
        d="M27.336 10.346l-.005.109c-.114-.207-.057-.157.005-.11zM12.65 27.843c-.04-.047-.001-.102.06-.163a2.92 2.92 0 0 0-.066.024c-.047-.045-.06-.087-.057-.126.056.018.11.044.166.061l-.042.041c.024-.008.053-.019.08-.027.028.007.056.01.084.018.051.064.1.129.132.159l-.178.019c-.09.006-.179-.006-.179-.006zm-5.943-3.481c.083.08.17.154.255.231l-.405-.017c.06-.034.104-.12.15-.214zm-3.269-3.653s-.157-.435-.153-.441c.067.089.179.241.296.405.062.26.124.52.19.773a1.467 1.467 0 0 1-.336-.566l.003-.17zm-1.682-2.087c-.008-.063-.048-.9.043-1.114a.146.146 0 0 1 .054-.074c.041.183.076.37.123.55l-.21.077.233-.003c.046.176.105.347.157.52-.16.06-.315.09-.4.044zM1.83 15.9c.048.011.095-.044.127-.084.014.134.03.267.05.4a1.143 1.143 0 0 1-.177-.316zm-.485-3.007c-.017-.49.087-.183.071-.271.087-.868-.18-.859-.006-1.547.11-.244.152.073.215.04-.02.38-.112.544-.124.807l.057-.302c.018.134.021.394-.01.522.01-.03.02-.086.03-.153a22.907 22.907 0 0 0-.062 1.819c-.074-.187-.139-.507-.17-.915zm.203-1.787l.005.014c-.128.232-.081.15-.005-.014zM4.49 6.54c-.106.14-.209.283-.31.426a.684.684 0 0 1 .31-.426zm9.749-5.528c-.17.118-.017.245.148.38-.244.002-.486-.005-.732.012-3.677.258-6.87 2.082-9.026 4.782.01-.012.02-.025.024-.04l-.055-.03c-.094.127-.128.232-.048.173-.09.117-.184.232-.27.351.09-.265-.293-.339-.612-.248.036.037.059.056-.052.358.096-.068.513-.47.435-.206-.2.352-.216.25-.376.38.177-.056-.044.413.053.544-.42.682-.78 1.403-1.071 2.16-.01-.021-.025-.03-.053-.008l-.062.217c-.186.152.001-.458-.154-.21.043-.31.013-.708.285-1.06l.188.002c-.047-.014-.218.207-.224.339.013-.198.5-.486.392-.764l-.24.216c.07-.31.065-.763.334-1.06-.236.064-.033.084-.346.224.32-.094-.464.896-.064.67-.323.154-.323.388-.635.66.055.012.146-.081 0 .218a.42.42 0 0 1 .019.087l-.013.02.013-.015c.002.016.003.018.004-.006.052-.064.102-.111.14-.123.057.204-.135.685-.135.871-.095.171-.031-.097-.125-.019 0 0 .003.28.01.28-.125-.016-.337.438-.28-.03l-.119.4c-.132.218-.257.54-.254.756-.061.19.045.521-.02.332l-.04.66h-.031c-.078.317-.037.657-.042 1 .001.345-.045.693-.134 1.063.035.219.078.441.05.806l-.104.078c.039.277-.016.852.102.96-.279.348.167 1.365.234 1.857l.139-.018c.074.331.23.627.408 1.007l.108-.066c.187.31.252.889.493 1.409-.058-.015-.106-.153-.12-.259.005.767.832 1.177.967 1.804.125.1.174.2.21.306a.128.128 0 0 0-.027-.028l.035.053.069.214a.92.92 0 0 0-.05-.186c.07.095.185.234.31.359l-.063.143.027.03c.06.174.128.075.155-.062.064.06.14.102.205.13-.076.244.348.3.298.597.08.007.238.16.403.3.18.125.367.236.481.182-.017.026.01.072-.058.01.118.152.237.306.405.377l-.055.184.226.06.235.044c.13.237.177.353-.103.294.603.227.434.26.958.414l-.084.076c.158.1.484.138.527.275.218.442 1.736 1.072 2.674 1.606-.092-.371.422.305.544.064.037.092.169.176-.017.19.546.077.761.373 1.181.221.046.088-.138.089-.092.144.047-.008.185-.033.232.023.047.056-.091.049-.185.065.561.093.653-.131.726-.345.256.162.4.165.615.031.087.08.242.17-.102.168.189.024 1.171.213 1.195.022.06.044.268.008.318-.013.43.003.468.018.89-.007l-.119-.027c.154-.21.344-.07.679-.137l-.007.023c.79.05.323-.089 1.107-.057l-.066-.123c.011-.299.694.018 1.108-.193l-.175-.037c.206-.143.755.168 1.012.125.06.007-.069.066-.136.109.68-.051.026-.194.471-.39.118.057-.024.273.291.166.183-.006.757-.663 1.225-.714-.12-.016-.235-.033-.066-.194.276-.197.954-.22 1.088-.597.047-.009.07-.002.082.011.184-.204.642-.584.694-.774.479.203 1.084-1.232 1.34-.941l.541-.612.018.044c.37-.37.386-.601.424-.803.096-.077.074.017.084.039.543-.543.544-.65.712-1.295l.151.017c.04-.17.73-.864.892-1.626.012.013.03.038.026.102.074-.43.37-.857.545-1.27.17-.41.284-.778.086-.988.015.002-.007-.572-.007-.572-.164.694-.192-.15-.324.12.02-.274.273-.675.238-.334l-.034.048c.228.175.255-.854.408-.814.157-1.41.224-2.813.024-4.15l-.17.186c.01-.002-.083-.455-.083-.455.02-.128.118-.194.182.135.073-.196-.214-.528-.258-.525-.063-.654.282.194.244-.001l-.075-.265-.008.066c-.138-.193-.196-.197-.316-.576-.04-.252.078-.16.054-.258.014-.004.01-.038-.042-.148l-.169-.568-.075.28c-.151-.221-.169-.522-.247-.205.064-.234-.142-.74-.35-1.223-.234-.471-.516-.891-.534-1.023a4.82 4.82 0 0 1-.72-.91c.036.11-.073.268-.268-.051.387-.125-.293-.644-.302-1.05.06.316-.754-.783-.645-.285-.204-.24.085-.11-.026-.342-.625-.433-1.162-1.215-1.975-1.703-.039.034.05.182-.156.133l-.282-.478c-.173-.075-.275.136-.491-.165.022.058.054.145-.062.102-1.501-1.124-3.432-1.291-5.203-1.898.242.117.074.111-.117.099.122.033-.012.12.007.19 0 0-.753-.258-.757-.242-.142.187-.827.027-.9.205l.24-.036z"
        fill={outer}
        fillRule="evenodd"
      />
    </Svg>
  );
}

export default ScorezeromarksIcon;
`

**LEGACY**

```
import React from "react";
import { Svg } from "expo";

function ScorezeromarksIcon({ style, outer }) {
  return (
    <Svg style={style} width="100%" height="100%" viewBox="0 0 29 29">
      <Svg.Path
        d="M27.336 10.346l-.005.109c-.114-.207-.057-.157.005-.11zM12.65 27.843c-.04-.047-.001-.102.06-.163a2.92 2.92 0 0 0-.066.024c-.047-.045-.06-.087-.057-.126.056.018.11.044.166.061l-.042.041c.024-.008.053-.019.08-.027.028.007.056.01.084.018.051.064.1.129.132.159l-.178.019c-.09.006-.179-.006-.179-.006zm-5.943-3.481c.083.08.17.154.255.231l-.405-.017c.06-.034.104-.12.15-.214zm-3.269-3.653s-.157-.435-.153-.441c.067.089.179.241.296.405.062.26.124.52.19.773a1.467 1.467 0 0 1-.336-.566l.003-.17zm-1.682-2.087c-.008-.063-.048-.9.043-1.114a.146.146 0 0 1 .054-.074c.041.183.076.37.123.55l-.21.077.233-.003c.046.176.105.347.157.52-.16.06-.315.09-.4.044zM1.83 15.9c.048.011.095-.044.127-.084.014.134.03.267.05.4a1.143 1.143 0 0 1-.177-.316zm-.485-3.007c-.017-.49.087-.183.071-.271.087-.868-.18-.859-.006-1.547.11-.244.152.073.215.04-.02.38-.112.544-.124.807l.057-.302c.018.134.021.394-.01.522.01-.03.02-.086.03-.153a22.907 22.907 0 0 0-.062 1.819c-.074-.187-.139-.507-.17-.915zm.203-1.787l.005.014c-.128.232-.081.15-.005-.014zM4.49 6.54c-.106.14-.209.283-.31.426a.684.684 0 0 1 .31-.426zm9.749-5.528c-.17.118-.017.245.148.38-.244.002-.486-.005-.732.012-3.677.258-6.87 2.082-9.026 4.782.01-.012.02-.025.024-.04l-.055-.03c-.094.127-.128.232-.048.173-.09.117-.184.232-.27.351.09-.265-.293-.339-.612-.248.036.037.059.056-.052.358.096-.068.513-.47.435-.206-.2.352-.216.25-.376.38.177-.056-.044.413.053.544-.42.682-.78 1.403-1.071 2.16-.01-.021-.025-.03-.053-.008l-.062.217c-.186.152.001-.458-.154-.21.043-.31.013-.708.285-1.06l.188.002c-.047-.014-.218.207-.224.339.013-.198.5-.486.392-.764l-.24.216c.07-.31.065-.763.334-1.06-.236.064-.033.084-.346.224.32-.094-.464.896-.064.67-.323.154-.323.388-.635.66.055.012.146-.081 0 .218a.42.42 0 0 1 .019.087l-.013.02.013-.015c.002.016.003.018.004-.006.052-.064.102-.111.14-.123.057.204-.135.685-.135.871-.095.171-.031-.097-.125-.019 0 0 .003.28.01.28-.125-.016-.337.438-.28-.03l-.119.4c-.132.218-.257.54-.254.756-.061.19.045.521-.02.332l-.04.66h-.031c-.078.317-.037.657-.042 1 .001.345-.045.693-.134 1.063.035.219.078.441.05.806l-.104.078c.039.277-.016.852.102.96-.279.348.167 1.365.234 1.857l.139-.018c.074.331.23.627.408 1.007l.108-.066c.187.31.252.889.493 1.409-.058-.015-.106-.153-.12-.259.005.767.832 1.177.967 1.804.125.1.174.2.21.306a.128.128 0 0 0-.027-.028l.035.053.069.214a.92.92 0 0 0-.05-.186c.07.095.185.234.31.359l-.063.143.027.03c.06.174.128.075.155-.062.064.06.14.102.205.13-.076.244.348.3.298.597.08.007.238.16.403.3.18.125.367.236.481.182-.017.026.01.072-.058.01.118.152.237.306.405.377l-.055.184.226.06.235.044c.13.237.177.353-.103.294.603.227.434.26.958.414l-.084.076c.158.1.484.138.527.275.218.442 1.736 1.072 2.674 1.606-.092-.371.422.305.544.064.037.092.169.176-.017.19.546.077.761.373 1.181.221.046.088-.138.089-.092.144.047-.008.185-.033.232.023.047.056-.091.049-.185.065.561.093.653-.131.726-.345.256.162.4.165.615.031.087.08.242.17-.102.168.189.024 1.171.213 1.195.022.06.044.268.008.318-.013.43.003.468.018.89-.007l-.119-.027c.154-.21.344-.07.679-.137l-.007.023c.79.05.323-.089 1.107-.057l-.066-.123c.011-.299.694.018 1.108-.193l-.175-.037c.206-.143.755.168 1.012.125.06.007-.069.066-.136.109.68-.051.026-.194.471-.39.118.057-.024.273.291.166.183-.006.757-.663 1.225-.714-.12-.016-.235-.033-.066-.194.276-.197.954-.22 1.088-.597.047-.009.07-.002.082.011.184-.204.642-.584.694-.774.479.203 1.084-1.232 1.34-.941l.541-.612.018.044c.37-.37.386-.601.424-.803.096-.077.074.017.084.039.543-.543.544-.65.712-1.295l.151.017c.04-.17.73-.864.892-1.626.012.013.03.038.026.102.074-.43.37-.857.545-1.27.17-.41.284-.778.086-.988.015.002-.007-.572-.007-.572-.164.694-.192-.15-.324.12.02-.274.273-.675.238-.334l-.034.048c.228.175.255-.854.408-.814.157-1.41.224-2.813.024-4.15l-.17.186c.01-.002-.083-.455-.083-.455.02-.128.118-.194.182.135.073-.196-.214-.528-.258-.525-.063-.654.282.194.244-.001l-.075-.265-.008.066c-.138-.193-.196-.197-.316-.576-.04-.252.078-.16.054-.258.014-.004.01-.038-.042-.148l-.169-.568-.075.28c-.151-.221-.169-.522-.247-.205.064-.234-.142-.74-.35-1.223-.234-.471-.516-.891-.534-1.023a4.82 4.82 0 0 1-.72-.91c.036.11-.073.268-.268-.051.387-.125-.293-.644-.302-1.05.06.316-.754-.783-.645-.285-.204-.24.085-.11-.026-.342-.625-.433-1.162-1.215-1.975-1.703-.039.034.05.182-.156.133l-.282-.478c-.173-.075-.275.136-.491-.165.022.058.054.145-.062.102-1.501-1.124-3.432-1.291-5.203-1.898.242.117.074.111-.117.099.122.033-.012.12.007.19 0 0-.753-.258-.757-.242-.142.187-.827.027-.9.205l.24-.036z"
        fill={outer}
        fillRule="evenodd"
      />
    </Svg>
  );
}

export default ScorezeromarksIcon;
```

**Comment by jonsamp** [comment]
Hi @RichardPK, thanks for the feedback. I just updated the package to import svg elements correctly: https://github.com/jonsamp/react-native-expo-svg/blob/master/index.js#L118

This will output code like:

```js
import { Svg, Path } from 'react-native-svg';
```

You can get the latest version `1.1.1` with: `npm i -g react-native-expo-svg`.

Please reopen an issue if you continue to see issues.
